export enum KeyCode {
	ArrowDown = 'ArrowDown',
	ArrowLeft = 'ArrowLeft',
	ArrowRight = 'ArrowRight',
	ArrowUp = 'ArrowUp',
	Digit = '1',
	KeyB = 'KeyB',
	KeyL = 'KeyL',
	KeyN = 'KeyN',
	KeyO = 'KeyO',
	KeyP = 'KeyP',
	KeyV = 'KeyV',
	Space = 'Space',
	Shift = 'Shift',
}
