#!/usr/bin/env sh

# update package.json version from ./public/manifest.json
. "$(dirname -- "$0")/set-version.sh"

# format files
npm run format

# add prettier changes
git add .

# create .zip file
./zip.sh
